public class RandomStudentSelector {
    public static void main(String[] args) {
        String[] students = {
                "Sana Daoud",
                "Ozden Firat",
                "Marcia Hamilton",
                "Miray Erbas",
                "Abdullah Ibrahim",
                "Yakeen Jaber",
                "Andre Ringo",
                "Ali Kokce",
                "Katelyn De Graaf",
                "Kendall Holmes",
                "Heba Rashed",
                "Vita Yuzko",
                "Sheker Hakberdiyeva",
                "LaToria Green",
                "Tasniem Hassan",
                "Taylor Green",
                "Sumeyye Feyza Ozbek",
                "Abdullah Wazwaz",
                "David Castellano",
                "Ibrahim Tawil",
                "Alona Fomina",
                "Daria Syvak",
                "Paulette Grandison",
                "Gulsum Batki",
                "Rami Turkmani",
                "Elena Sargazyan",
                "Radni Youhaneh",
                "Naim Abdullah",
                "Ismail Tawil",
                "Salah Musleh",
                "David Lopez Palmerin",
                "Nicholas Bayless",
                "Loretta Echols",
                "Kerem Nergiz",
                "Oluwaseun Florence Onibokun-Oni",
                "Deniz Taskin",
                "Meldag Sav",
                "Adenike S. Apapa",
                "Uthman Musleh",
                "Reem Al-Sheikh",
                "Basem Amra",
                "Guluzar Incekara",
                "Ahmad Amin",
                "Chriskaly Ngo",
                "Roza Ismayilova",
                "Andrei Mitioglo",
                "Regina Biktimirova",
                "Diana Safarova",
                "Alina Zhakypbek Kyzy",
                "Datkaiym Borbieva",
                "Fatma Yildiz",
                "Abraham Kim",
                "Yousef M Saleh",
                "Mohammed Abedrabbo",
                "Ulas Varli",
                "Nataliia Grynda",
                "Jonathan Ochoa"
        };

        System.out.println(students[(int) (Math.random() * 57)]);
    }
}
